In [1]:
import numpy as np

In [12]:
arr_1 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])  # dtype can be given as a parameter
print(arr_1.shape)
print(arr_1)

(9,)
[10 20 30 40 50 60 70 80 90]


In [4]:
arr_2 = np.array([[10], [20], [30], [40], [50]])
print(arr_2.shape)
print(arr_2)

(5, 1)
[[10]
 [20]
 [30]
 [40]
 [50]]


In [13]:
print(arr_1.dtype)
print(arr_1.itemsize)
print(arr_1.size)
print(arr_1.ndim)
print(arr_1.nbytes)


int64
8
9
1
72


In [3]:
# types of numpy arrays

# 1. create 1D array
array = np.array([10, 54, 65, 49, 25, 45, 90])

# 2. create 2D array
array = np.array([[8, 11, 13, 15], [14, 5, 19, 13], [34, 12, 153, 4]])
print(array.shape)
print(array.ndim)
print(array.itemsize)
print()


# 3. 3D array - the array is wrong
# array = np.array([[[8, 11, 13, 15],  [34, 12, 153, 4]]])
# below one is correct ig
array = np.array([[[8, 11, 13, 15],  [34, 12, 153, 4]], [[8, 11, 13, 15],  [34, 12, 153, 4]]])
print(array.shape)
print(array.ndim)
print(array.itemsize)

(3, 4)
2
8

(2, 2, 4)
3
8


In [26]:
# slicing and indexing in numpy array

array_2d = np.array([[8, 11, 13, 15], [14, 5, 19, 13], [34, 12, 153, 4]])
print(array_2d[0])  # first row only
print()

# all rows and all columns
print(array_2d[:, :])
print()

# first column only
print(array_2d[:, 0])
print()

# first two columns
print(array_2d[:, 0:2])
print()


# reject first and last rows and columns
print(array_2d[1:-1, 1:-1])
print()


# flipped matrix
print(array_2d[::-1, ::-1])
print()


[ 8 11 13 15]

[[  8  11  13  15]
 [ 14   5  19  13]
 [ 34  12 153   4]]

[[  8  11  13  15]
 [ 14   5  19  13]
 [ 34  12 153   4]]

[ 8 14 34]

[[ 8 11]
 [14  5]
 [34 12]]

[[ 5 19]]

[[  4 153  12  34]
 [ 13  19   5  14]
 [ 15  13  11   8]]



In [34]:
arr_3d = np.array([[[8, 11, 13, 15],  [34, 12, 153, 4]], [[81, 12, 23, 22],  [4, 4, 189, 14]]])
print(arr_3d)
print()

print(arr_3d[1])

[[[  8  11  13  15]
  [ 34  12 153   4]]

 [[  8  11  13  15]
  [ 34  12 153   4]]]

[[  8  11  13  15]
 [ 34  12 153   4]]


### ways to create a numpy array

In [39]:
# 

# 1. using arrange function
arr_1 = np.arange(1,51)
print(arr_1)

arr_1 = arr_1.reshape(2,5,5)
print(arr_1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]
  [21 22 23 24 25]]

 [[26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]
  [41 42 43 44 45]
  [46 47 48 49 50]]]


In [43]:
# 2. zero matrix

arr_2 = np.zeros((3, 4), dtype="int16")
print(arr_2)
print()

# type casting form int to float
print(arr_2.astype("float32"))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [44]:
# 3. ones matrix
arr_3 = np.ones((5, 5))
print(arr_3)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [45]:
# 4.identity matrix

# square matrix
arr_4 = np.identity(7)
print(arr_4)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [48]:
# 5. empty matrix

# can be filled with any value
arr_5 = np.empty((6, 1))
print(arr_5)
print()
print()

# fill all positions with some particular value
arr_5.fill(2)
print(arr_5)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


[[2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]]


In [5]:
# 6. full

arr_6 = np.full((10,2), 4.4)
print(arr_6)

[[4.4 4.4]
 [4.4 4.4]
 [4.4 4.4]
 [4.4 4.4]
 [4.4 4.4]
 [4.4 4.4]
 [4.4 4.4]
 [4.4 4.4]
 [4.4 4.4]
 [4.4 4.4]]


In [7]:
# 7. linspace

# create array with evenly spaced elements
print(np.linspace(10, 100, 10))

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [58]:
# 8. logspace

# elements evenly spaced on a log scale
print(np.logspace(0, 1, 10, base=10))


[ 1.          1.29154967  1.66810054  2.15443469  2.7825594   3.59381366
  4.64158883  5.9948425   7.74263683 10.        ]


Exercise

1. program that will generate output like: 
[[1 1 1 1 1 1 1 1 1 1]
[1 0 0 0 0 0 0 0 0 1]
[1 0 0 0 0 0 0 0 0 1]
[1 0 0 0 0 0 0 0 0 1]
[1 0 0 0 0 0 0 0 0 1]
[1 0 0 0 0 0 0 0 0 1]
[1 0 0 0 0 0 0 0 0 1]
[1 0 0 0 0 0 0 0 0 1]
[1 0 0 0 0 0 0 0 0 1]
[1 1 1 1 1 1 1 1 1 1]]

2. create checker box
[1 0 1 0 1 0 1 0 1 0 1]
[0 1 0 1 0 1 0 1 0 1 0]
[1 0 1 0 1 0 1 0 1 0 1]
[0 1 0 1 0 1 0 1 0 1 0]
[1 0 1 0 1 0 1 0 1 0 1]
[0 1 0 1 0 1 0 1 0 1 0]
[1 0 1 0 1 0 1 0 1 0 1]
[0 1 0 1 0 1 0 1 0 1 0]
[1 0 1 0 1 0 1 0 1 0 1]
[0 1 0 1 0 1 0 1 0 1 0]

In [63]:
# Exercise 1 answer:

arr = np.ones((10, 10), dtype="int16")
arr[1:-1, 1:-1] = 0
print(arr)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [92]:
# Exercise 2 answer
arr = np.ones((10, 11), dtype="int16")
arr[::2, ::2] = 0
arr[1::2, 1::2] = 0

print(arr)

[[0 1 0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1 0 1]]


## Mathematical operations on NumPy array

In [100]:
arr1 = np.array([[[1, 3, 5],
          [4, 8, 7],
          [9, 11, 13]],
          [[1, 3, 5],
          [4, 8, 7],
          [9, 11, 13]]])
print(arr1.sum())
print(arr1.sum(axis=0)) # position-wise addition [kinda overlap the 2 matrices]
print(arr1.sum(axis=1)) # add everything in a column, per matrix
print(arr1.sum(axis=2)) # add everything in a row, per matrix



122
[[ 2  6 10]
 [ 8 16 14]
 [18 22 26]]
[[14 22 25]
 [14 22 25]]
[[ 9 19 33]
 [ 9 19 33]]


In [105]:
print(arr1.min())
print(arr1.max())
print()
print()

arr_14 = np.arange(1, 21).reshape(5, 4)
print(arr_14)
print(np.where(arr_14 >= 8))


1
13


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
(array([1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4]), array([3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))


In [107]:
# statistical methods

arr_15 = np.arange(1, 37).reshape(6, 6)
print(arr_15.mean())
print(arr_15.mean(axis=0))
print(arr_15.mean(axis=1))


18.5
[16. 17. 18. 19. 20. 21.]
[ 3.5  9.5 15.5 21.5 27.5 33.5]


In [110]:
arr_15 = np.arange(1, 37).reshape(6, 6)
print(arr_15.std())
print(arr_15.var())


10.388294694831615
107.91666666666667


In [111]:
# reversing an array

arr_16 = np.arange(50)
print(arr_16)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [116]:
print(np.flip(arr_16))
print(np.flipud(arr_15))
print(np.fliplr(arr_15))
print(np.flip(arr_15))

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]
[[31 32 33 34 35 36]
 [25 26 27 28 29 30]
 [19 20 21 22 23 24]
 [13 14 15 16 17 18]
 [ 7  8  9 10 11 12]
 [ 1  2  3  4  5  6]]
[[ 6  5  4  3  2  1]
 [12 11 10  9  8  7]
 [18 17 16 15 14 13]
 [24 23 22 21 20 19]
 [30 29 28 27 26 25]
 [36 35 34 33 32 31]]
[[36 35 34 33 32 31]
 [30 29 28 27 26 25]
 [24 23 22 21 20 19]
 [18 17 16 15 14 13]
 [12 11 10  9  8  7]
 [ 6  5  4  3  2  1]]


In [126]:
# flatten() - convert nD array to a 1D array

arr = np.random.randint(10, 50, size=(5, 3))
print(arr)
print(arr.flatten())

[[10 47 26]
 [10 14 23]
 [44 24 38]
 [41 45 39]
 [33 43 13]]
[10 47 26 10 14 23 44 24 38 41 45 39 33 43 13]


In [127]:
# ravel() flattens nD array to 1D array

print(arr.ravel())

[10 47 26 10 14 23 44 24 38 41 45 39 33 43 13]


In [135]:
# np.argmax - max value from np array
# but for higher dimension, index value is not proper - it counts after flattening

arr = np.random.randint(10, 50, size=(5, ))
print(arr)
print(np.argmax(arr))
print(np.argmin(arr))

[40 20 45 45 14]
2
4


In [ ]:
# array broadcasting

# 